name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build-node-version: ['14']

    concurrency:
      group: build-${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Reusable Workflow
        uses: ./.github/workflows/build-test
